# .github/workflows/test-repository-dispatch-2.yml
name: Repository Dispatch Test 2

on:
  repository_dispatch:
    types: ['vercel.deployment.success']
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "Preview"

jobs:
  test:
    runs-on: ubuntu-latest
    # no environment
    steps:
      - name: Check deployment status
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "State: ${{ github.event.deployment_status.state }}"
          echo "Environment: ${{ github.event.deployment.environment }}"
          echo "URL: ${{ github.event.deployment_status.target_url }}"
